#!/usr/bin/env php


<?php
// Tambal konstanta sinyal di Windows (karena ext-pcntl tidak ada)
if (DIRECTORY_SEPARATOR === '\\') {
    if (!defined('SIGINT'))  define('SIGINT', 2);
    if (!defined('SIGTERM')) define('SIGTERM', 15);
    if (!defined('SIGHUP'))  define('SIGHUP', 1);
}


use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
